import turtle
turtle.shape("turtle")
turtle.pensize(6)
for i in range(6):
    turtle.fd(100)
    turtle.rt(60)
turtle.rt(60)
turtle.fd(200)
turtle.pu()
turtle.setpos(100,0)
turtle.pd()
turtle.rt(60)
turtle.fd(200)
turtle.pu()
turtle.bk(100)
turtle.pd()
turtle.rt(60)
turtle.fd(100)
turtle.ht()
