import turtle
turtle.shape("turtle")
turtle.pensize(4)
turtle.circle(50)
turtle.pu()
turtle.setpos(-20, 60)
turtle.pd()
turtle.circle(5)
turtle.pu()
turtle.setpos(20, 60)
turtle.pd()
turtle.circle(5)
turtle.pu()
turtle.setpos(-20, 35)
turtle.pd()
turtle.rt(90)
turtle.circle(20, 180)
turtle.ht()
